name: GitHub Actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test TypeScript
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install -g yarn
      - name: yarn test
        run: yarn && yarn test && yarn tsc
